# Generated by Django 4.1.5 on 2023-01-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
